-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로
SELECT B.ANIMAL_ID,B.NAME 
FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID 
WHERE A.DATETIME IS NULL ORDER BY B.ANIMAL_ID ASC;