-- 코드를 입력하세요
# SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%y-%M-%D') AS PUBLISHED_DATE
# FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE B.CATEGORY = '경제'
# ORDER BY B.PUBLISHED_DATE

SELECT 
    BO.BOOK_ID, 
    AU.AUTHOR_NAME, 
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR AU 
INNER JOIN BOOK BO
 ON AU.AUTHOR_ID = BO.AUTHOR_ID
WHERE BO.CATEGORY LIKE '경제'
ORDER BY BO.PUBLISHED_DATE ASC;